MODEL:
  PRETRAIN_PATH: '/storage/huytq14/multpersonTracking/SOLIDER-REID/base_weights/swin_tiny_tea.pth'
  SEMANTIC_WEIGHT: 0.2
  PRETRAIN_HW_RATIO: 2
  METRIC_LOSS_TYPE: 'triplet'
  IF_LABELSMOOTH: 'on'
  IF_WITH_CENTER: 'yes'
  NAME: 'transformer'
  NO_MARGIN: True
  DEVICE_ID: ('3')
  TRANSFORMER_TYPE: 'swin_small_patch4_window7_224'
  STRIDE_SIZE: [16, 16]
INPUT:
  SIZE_TRAIN: [384, 128]
  SIZE_TEST: [384, 128]
  PROB: 0.5 # random horizontal flip
  RE_PROB: 0.5 # random erasing
  PADDING: 10
  PIXEL_MEAN: [0.5, 0.5, 0.5]
  PIXEL_STD: [0.5, 0.5, 0.5]

DATASETS:
  NAMES: ('cuhk03')
  # NAMES: ['CelebReID','market1501']
  ROOT_DIR: ('/storage/huytq14/multpersonTracking/SOLIDER-REID/train_data')

DATALOADER:
  SAMPLER: 'softmax_triplet'
  NUM_INSTANCE: 4
  NUM_WORKERS: 8

SOLVER:
  OPTIMIZER_NAME: 'SGD'
  MAX_EPOCHS: 250
  BASE_LR: 0.001
  WARMUP_EPOCHS: 5
  IMS_PER_BATCH: 64
  WARMUP_METHOD: 'cosine'
  LARGE_FC_LR: False
  CHECKPOINT_PERIOD: 10
  LOG_PERIOD: 10
  EVAL_PERIOD: 10
  WEIGHT_DECAY:  1e-4
  WEIGHT_DECAY_BIAS: 1e-4
  BIAS_LR_FACTOR: 2

TEST:
  EVAL: True
  IMS_PER_BATCH: 128
  RE_RANKING: True
  WEIGHT: '/storage/huytq14/multpersonTracking/SOLIDER-REID/log/full_data/swin_tiny_market1501/transformer_250.pth'
  NECK_FEAT: 'before'
  FEAT_NORM: 'yes'

OUTPUT_DIR: './log/cuhk03/swin_tiny_paper/'
